### ISSUE TITLE
[FAQ] 字體太大，會爆出圖片

### ISSUE THREAD

**Issue by Ankarrr** [aidanholm/bb_site#1]
Browser: Chrome
Also heard this issue in Safari, but I don't get the screen shot.
![faq-bug](https://cloud.githubusercontent.com/assets/8311552/7426924/33ddd986-f003-11e4-860b-bbc8254302ea.png)

**Comment by aidanholm** [comment]
Currently converting pixel based units to relative units; this should fix this issue
